class AuthError(Exception):
    pass

class BadResponse(Exception):
    pass